#!/bin/sh

set -e

case "$1" in
  purge|remove)
  if [ -x /etc/init.d/pulseaudio-enable-autospawn ]; then
  	if [ -x /usr/sbin/update-rc.d ]; then
    	update-rc.d /etc/init.d/pulseaudio-enable-autospawn defaults >/dev/null 2>&1
  	fi
  fi
  
  ;;
  *) exit 0
esac


exit 0
