#!/bin/sh

set -e

if [ "$1" = "purge" | "$1" = "remove"] ; then
  if [ -x /etc/init.d/pulseaudio-enable-autospawn ]; then
  	if [ -x /usr/sbin/update-rc.d ]; then
    	update-rc.d /etc/init.d/pulseaudio-enable-autospawn defaults >/dev/null 2>&1
  	fi
  fi
fi

exit 0
